---
version: '3.7'
services:

  bm-postgre:
    container_name: bm-postgre
    image: postgres:14
    networks:
      - bm-backend
    volumes:
      - ./docker-volumes/bm-postgre:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:  
      - ${DB_PORT}:5432
    restart: unless-stopped
  
  bm-adminer:
    container_name: bm-adminer
    image: adminer
    restart: always
    networks:
      - bm-backend
    environment: 
      ADMINER_DESIGN: dracula
      ADMINER_DEFAULT_SERVER: bm-postgre
    depends_on: 
      - bm-postgre
    ports:
      - 9999:8080

networks:
  bm-backend: {}